on: [push, pull_request]
name: build
jobs:
  unit_test:
    if: (github.repository == 'kubernetes-sigs/cluster-api-provider-kubemark')
    strategy:
      matrix:
        go-version: [1.19.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Test
      run: make test
    - name: Build
      run: make manager

  go-linter:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v2
      with: # TODO: remove this when the deprecated function will be removed (issue #85)
        args: --exclude SA1019 --timeout=5m
